# Generated by Django 3.2.7 on 2022-02-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_orderitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(max_length=14)),
                ('home_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=25)),
                ('age', models.IntegerField(max_length=2)),
            ],
        ),
    ]
